# Generated by Django 4.0.1 on 2022-01-27 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('nascimento', models.DateTimeField()),
                ('estado_civil', models.CharField(choices=[('C', 'Casado'), ('S', 'Solteiro'), ('D', 'Divorciado'), ('A', 'Amasiado')], max_length=1)),
                ('cpf', models.IntegerField()),
                ('identidade', models.IntegerField()),
                ('orgao_emissor', models.CharField(max_length=50)),
                ('data_expedicao', models.DateTimeField()),
                ('endereco', models.TextField()),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
