# Generated by Django 4.0.1 on 2022-01-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='telefone',
            field=models.CharField(default='63 45684-4654', max_length=20),
            preserve_default=False,
        ),
    ]
