# Generated by Django 4.0.1 on 2022-01-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0003_remove_beneficiario_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='data_expedicao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nascimento',
            field=models.DateField(),
        ),
    ]
